// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBra80mzL_Pdp5fZOjn_muHNG17w3_enKU',
    appId: '1:223695866051:web:2676b4437d85bd9edf7a76',
    messagingSenderId: '223695866051',
    projectId: 'my-application-genesis',
    authDomain: 'my-application-genesis.firebaseapp.com',
    storageBucket: 'my-application-genesis.appspot.com',
    measurementId: 'G-BMFT2JXLNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAge2q47Vb_Xu16clEEvjFyZQ7Z540elAU',
    appId: '1:223695866051:android:34b99aacca2c3131df7a76',
    messagingSenderId: '223695866051',
    projectId: 'my-application-genesis',
    storageBucket: 'my-application-genesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJEyM5GY28QFAKyTuIfGk5q6dfScJSiIg',
    appId: '1:223695866051:ios:812458aad516defedf7a76',
    messagingSenderId: '223695866051',
    projectId: 'my-application-genesis',
    storageBucket: 'my-application-genesis.appspot.com',
    iosBundleId: 'com.example.myApplicationGenesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJEyM5GY28QFAKyTuIfGk5q6dfScJSiIg',
    appId: '1:223695866051:ios:9eb7084e09a7df5adf7a76',
    messagingSenderId: '223695866051',
    projectId: 'my-application-genesis',
    storageBucket: 'my-application-genesis.appspot.com',
    iosBundleId: 'com.example.myApplicationGenesis.RunnerTests',
  );
}
